/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_okunu_app_gaussblur_BlurJni */

#ifndef _Included_com_okunu_app_gaussblur_BlurJni
#define _Included_com_okunu_app_gaussblur_BlurJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_okunu_app_gaussblur_BlurJni
 * Method:    blurIntArray
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_okunu_app_gaussblur_BlurJni_blurIntArray
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_okunu_app_gaussblur_BlurJni
 * Method:    blurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_okunu_app_gaussblur_BlurJni_blurBitmap
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
