/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ok_com_asapp_MainActivity */

#ifndef _Included_ok_com_asapp_MainActivity
#define _Included_ok_com_asapp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

#include <android/log.h>
#include <android/bitmap.h>
#include <math.h>
#define LOG_TAG "okunu"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,LOG_TAG, __VA_ARGS__)

/*
 * Class:     ok_com_asapp_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ok_com_asapp_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     ok_com_asapp_MainActivity
 * Method:    gaussBlue
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_ok_com_asapp_MainActivity_gaussBlue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ok_com_asapp_MainActivity
 * Method:    blurIntArray
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_ok_com_asapp_MainActivity_blurIntArray
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
